# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UFPR-Lamind

description: > # this means to ignore newlines until "baseurl:"
  Laborátorio da Matemática Industrial da Universidade Federal do Paraná - 2018
#url: "https://github.com/ufpr-lamind"
github_username:  ufpr-lamind

# Build settings
coordenador: Abel Soares Siqueira
estagiario: Filipe Fenrich Niespodzinski
estagiario: Julio Parodi
estagiario: Renan Oclides
